// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "d0309b24-fb9b-45cb-944e-0dcb87d32b88";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onManualAngleChange();
void onIsAutoModeChange();

float angle;
float current;
float power;
float voltage;
int manualAngle;
bool isAutoMode;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(angle, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(current, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(power, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(voltage, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(manualAngle, READWRITE, ON_CHANGE, onManualAngleChange);
  ArduinoCloud.addProperty(isAutoMode, READWRITE, ON_CHANGE, onIsAutoModeChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
